# This file was generated by GoReleaser. DO NOT EDIT.
cask "ecctl" do
  version "0.2.4"

  on_macos do
    on_intel do
      sha256 "c8d971d1a0252f80e631cb28b9c89424b00eaf7d160009d0d20d86f4cef6014a"
      url "https://ros-public-tools.oss-cn-beijing.aliyuncs.com/github-releases/aliyun/elastic-compute-control-cli/#{version}/ecctl_#{version}_darwin_amd64.tar.gz",
        verified: "ros-public-tools.oss-cn-beijing.aliyuncs.com/github-releases/aliyun/elastic-compute-control-cli/"
    end
    on_arm do
      sha256 "aecc93c390fe1b90abba484ff926ee5f5fc6786d06effbd5d927d47b06e81b58"
      url "https://ros-public-tools.oss-cn-beijing.aliyuncs.com/github-releases/aliyun/elastic-compute-control-cli/#{version}/ecctl_#{version}_darwin_arm64.tar.gz",
        verified: "ros-public-tools.oss-cn-beijing.aliyuncs.com/github-releases/aliyun/elastic-compute-control-cli/"
    end
  end

  name "ecctl"
  desc "Agent-first command-line controller for Alibaba Cloud elastic computing resources"
  homepage "https://github.com/aliyun/elastic-compute-control-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ecctl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ecctl"]
  end

  # No zap stanza required

end
