# This file was generated by GoReleaser. DO NOT EDIT.
cask "ecctl" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "7332694eea1e83bf61d01b65f4b28abc7dc4e22aac9afd4b07c7d3167052e526"
      url "https://github.com/aliyun/elastic-compute-control-cli/releases/download/v#{version}/ecctl_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/aliyun/elastic-compute-control-cli/"
    end
    on_arm do
      sha256 "6a4fb8d1e1467d1242cd563427311d6b7f926141e2cb2e39d582fd7e3d8422b7"
      url "https://github.com/aliyun/elastic-compute-control-cli/releases/download/v#{version}/ecctl_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/aliyun/elastic-compute-control-cli/"
    end
  end

  name "ecctl"
  desc "Agent-first command-line controller for Alibaba Cloud elastic computing resources"
  homepage "https://github.com/aliyun/elastic-compute-control-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ecctl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ecctl"]
  end

  # No zap stanza required

end
