# This file was generated by GoReleaser. DO NOT EDIT.
cask "ecctl" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "36271237bd4345b5432c554055f8454effd7df78ea6b4bff925fb382d6fa8664"
      url "https://ros-public-tools.oss-cn-beijing.aliyuncs.com/github-releases/aliyun/elastic-compute-control-cli/#{version}/ecctl_#{version}_darwin_amd64.tar.gz",
        verified: "ros-public-tools.oss-cn-beijing.aliyuncs.com/github-releases/aliyun/elastic-compute-control-cli/"
    end
    on_arm do
      sha256 "4790557c8ab071d158eff28e762fbcab8fe2aa0f1ec8c447b99290d840fdd150"
      url "https://ros-public-tools.oss-cn-beijing.aliyuncs.com/github-releases/aliyun/elastic-compute-control-cli/#{version}/ecctl_#{version}_darwin_arm64.tar.gz",
        verified: "ros-public-tools.oss-cn-beijing.aliyuncs.com/github-releases/aliyun/elastic-compute-control-cli/"
    end
  end

  name "ecctl"
  desc "Agent-first command-line controller for Alibaba Cloud elastic computing resources"
  homepage "https://github.com/aliyun/elastic-compute-control-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ecctl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ecctl"]
  end

  # No zap stanza required

end
