package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"github.com/aliyun/elastic-compute-control-cli/pkg/spec"
)

type catalogData struct {
	refs      []spec.ResourceRef
	resources []resourceEntry
	products  []spec.ProductSpec
}

type resourceEntry struct {
	product  string
	resource string
	parent   string
	spec     spec.ResourceSpec
}

func main() {
	specDir := flag.String("spec-dir", "specs", "path to spec YAML directory")
	out := flag.String("out", "pkg/spec/catalog_generated.go", "output file path")
	check := flag.Bool("check", false, "check if generated file is up-to-date")
	flag.Parse()

	data, err := loadCatalog(*specDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "specgen: %v\n", err)
		os.Exit(1)
	}

	generated, err := generate(data)
	if err != nil {
		fmt.Fprintf(os.Stderr, "specgen: %v\n", err)
		os.Exit(1)
	}

	formatted, err := format.Source(generated)
	if err != nil {
		fmt.Fprintf(os.Stderr, "specgen: gofmt failed: %v\n", err)
		os.Exit(1)
	}

	if *check {
		existing, err := os.ReadFile(*out)
		if err != nil {
			fmt.Fprintf(os.Stderr, "specgen: cannot read %s: %v\n", *out, err)
			os.Exit(1)
		}
		if !bytes.Equal(existing, formatted) {
			fmt.Fprintf(os.Stderr, "specgen: %s is out of date; run 'make generate'\n", *out)
			os.Exit(1)
		}
		return
	}

	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "specgen: %v\n", err)
		os.Exit(1)
	}
}

func loadCatalog(specDir string) (*catalogData, error) {
	data := &catalogData{}
	refSet := map[spec.ResourceRef]bool{}
	productSet := map[string]bool{}

	err := filepath.WalkDir(specDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || filepath.Ext(path) != ".yaml" {
			return nil
		}
		raw, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return addRaw(data, refSet, productSet, raw)
	})
	if err != nil {
		return nil, err
	}
	resources := make([]spec.ResourceSpec, 0, len(data.resources))
	for _, entry := range data.resources {
		resources = append(resources, entry.spec)
	}
	if err := spec.ValidateSchemaPaths(resources); err != nil {
		return nil, err
	}

	sort.Slice(data.refs, func(i, j int) bool {
		if data.refs[i].Product != data.refs[j].Product {
			return data.refs[i].Product < data.refs[j].Product
		}
		return data.refs[i].Resource < data.refs[j].Resource
	})
	sort.Slice(data.resources, func(i, j int) bool {
		if data.resources[i].product != data.resources[j].product {
			return data.resources[i].product < data.resources[j].product
		}
		return data.resources[i].resource < data.resources[j].resource
	})
	sort.Slice(data.products, func(i, j int) bool {
		return data.products[i].Product < data.products[j].Product
	})
	return data, nil
}

func addRaw(data *catalogData, refSet map[spec.ResourceRef]bool, productSet map[string]bool, raw []byte) error {
	loaded, err := spec.Load(raw)
	if err != nil {
		if product, ok := loadValidProduct(raw); ok {
			addProduct(data, productSet, product)
			return nil
		}
		return err
	}
	if loaded.Product != "" && loaded.Resource != "" {
		ref := spec.ResourceRef{Product: loaded.Product, Resource: loaded.Resource, Parent: loaded.Parent}
		if !refSet[ref] {
			refSet[ref] = true
			data.refs = append(data.refs, ref)
		}
		if err := spec.Validate(loaded); err == nil {
			data.resources = append(data.resources, resourceEntry{
				product:  loaded.Product,
				resource: loaded.Resource,
				parent:   loaded.Parent,
				spec:     loaded,
			})
		}
		return nil
	}
	if loaded.Product != "" && loaded.Resource == "" {
		if product, ok := loadValidProduct(raw); ok {
			addProduct(data, productSet, product)
		}
	}
	return nil
}

func loadValidProduct(raw []byte) (spec.ProductSpec, bool) {
	product, err := spec.LoadProductSpec(raw)
	if err != nil || product.Product == "" {
		return spec.ProductSpec{}, false
	}
	if err := spec.ValidateProduct(product); err != nil {
		return spec.ProductSpec{}, false
	}
	return product, true
}

func addProduct(data *catalogData, productSet map[string]bool, product spec.ProductSpec) {
	if productSet[product.Product] {
		return
	}
	productSet[product.Product] = true
	data.products = append(data.products, product)
}

func generate(data *catalogData) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/specgen. DO NOT EDIT.\n\npackage spec\n\n")
	buf.WriteString("func generatedCatalog() *specCacheEntry {\n")
	buf.WriteString("\treturn &specCacheEntry{\n")

	buf.WriteString("\t\trefs: []ResourceRef{\n")
	for _, ref := range data.refs {
		buf.WriteString("\t\t\t{Product: ")
		writeGoString(&buf, ref.Product)
		buf.WriteString(", Resource: ")
		writeGoString(&buf, ref.Resource)
		if ref.Parent != "" {
			buf.WriteString(", Parent: ")
			writeGoString(&buf, ref.Parent)
		}
		buf.WriteString("},\n")
	}
	buf.WriteString("\t\t},\n")

	buf.WriteString("\t\tresources: map[resourceKey]ResourceSpec{\n")
	for _, entry := range data.resources {
		buf.WriteString("\t\t\t{product: ")
		writeGoString(&buf, entry.product)
		buf.WriteString(", resource: ")
		writeGoString(&buf, entry.resource)
		if entry.parent != "" {
			buf.WriteString(", parent: ")
			writeGoString(&buf, entry.parent)
		}
		buf.WriteString("}: ")
		writeLiteral(&buf, reflect.ValueOf(entry.spec), 3)
		buf.WriteString(",\n")
	}
	buf.WriteString("\t\t},\n")

	buf.WriteString("\t\tproducts: map[string]ProductSpec{\n")
	for _, product := range data.products {
		buf.WriteString("\t\t\t")
		writeGoString(&buf, product.Product)
		buf.WriteString(": ")
		writeLiteral(&buf, reflect.ValueOf(product), 3)
		buf.WriteString(",\n")
	}
	buf.WriteString("\t\t},\n")

	buf.WriteString("\t}\n}\n\n")
	buf.WriteString("func intPtr(v int) *int { return &v }\n")
	return buf.Bytes(), nil
}

func writeLiteral(buf *bytes.Buffer, v reflect.Value, depth int) {
	switch v.Kind() {
	case reflect.Ptr:
		if v.IsNil() {
			buf.WriteString("nil")
			return
		}
		elem := v.Elem()
		switch elem.Kind() {
		case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
			fmt.Fprintf(buf, "intPtr(%d)", elem.Int())
			return
		case reflect.Struct:
			buf.WriteString("&")
			writeTypeName(buf, elem.Type())
			writeLiteralBody(buf, elem, depth)
		default:
			fmt.Fprintf(buf, "/* unsupported ptr to %s */nil", elem.Type())
		}

	case reflect.Interface:
		if v.IsNil() {
			buf.WriteString("nil")
			return
		}
		writeLiteral(buf, v.Elem(), depth)

	case reflect.Struct:
		writeTypeName(buf, v.Type())
		writeLiteralBody(buf, v, depth)

	case reflect.Map:
		if v.IsNil() || v.Len() == 0 {
			buf.WriteString("nil")
			return
		}
		writeTypeName(buf, v.Type())
		writeMapLiteral(buf, v, depth)

	case reflect.Slice:
		if v.IsNil() || v.Len() == 0 {
			buf.WriteString("nil")
			return
		}
		writeTypeName(buf, v.Type())
		buf.WriteString("{")
		for i := 0; i < v.Len(); i++ {
			if i > 0 {
				buf.WriteString(", ")
			}
			writeLiteral(buf, v.Index(i), depth+1)
		}
		buf.WriteString("}")

	case reflect.String:
		writeGoString(buf, v.String())

	case reflect.Bool:
		if v.Bool() {
			buf.WriteString("true")
		} else {
			buf.WriteString("false")
		}

	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		fmt.Fprintf(buf, "%d", v.Int())

	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		fmt.Fprintf(buf, "%d", v.Uint())

	case reflect.Float32, reflect.Float64:
		f := v.Float()
		if f == float64(int64(f)) {
			fmt.Fprintf(buf, "float64(%d)", int64(f))
		} else {
			fmt.Fprintf(buf, "%v", f)
		}

	default:
		fmt.Fprintf(buf, "%#v", v.Interface())
	}
}

func writeLiteralBody(buf *bytes.Buffer, v reflect.Value, depth int) {
	t := v.Type()
	buf.WriteString("{")
	first := true
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		if !field.IsExported() {
			continue
		}
		fv := v.Field(i)
		if isZeroValue(fv) {
			continue
		}
		if !first {
			buf.WriteString(", ")
		}
		first = false
		buf.WriteString(field.Name)
		buf.WriteString(": ")
		writeLiteral(buf, fv, depth+1)
	}
	buf.WriteString("}")
}

func writeMapLiteral(buf *bytes.Buffer, v reflect.Value, depth int) {
	buf.WriteString("{")
	keys := sortMapKeys(v)
	for i, key := range keys {
		if i > 0 {
			buf.WriteString(", ")
		}
		writeLiteral(buf, key, depth+1)
		buf.WriteString(": ")
		writeLiteral(buf, v.MapIndex(key), depth+1)
	}
	buf.WriteString("}")
}

func sortMapKeys(v reflect.Value) []reflect.Value {
	keys := v.MapKeys()
	sort.Slice(keys, func(i, j int) bool {
		ki, kj := keys[i], keys[j]
		switch ki.Kind() {
		case reflect.String:
			return ki.String() < kj.String()
		case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
			return ki.Int() < kj.Int()
		default:
			return fmt.Sprint(ki.Interface()) < fmt.Sprint(kj.Interface())
		}
	})
	return keys
}

func writeTypeName(buf *bytes.Buffer, t reflect.Type) {
	name := t.Name()
	if name != "" {
		pkg := t.PkgPath()
		if strings.HasSuffix(pkg, "/spec") || pkg == "" {
			buf.WriteString(name)
		} else {
			buf.WriteString(t.String())
		}
		return
	}
	switch t.Kind() {
	case reflect.Map:
		buf.WriteString("map[")
		writeTypeName(buf, t.Key())
		buf.WriteString("]")
		writeTypeName(buf, t.Elem())
	case reflect.Slice:
		buf.WriteString("[]")
		writeTypeName(buf, t.Elem())
	case reflect.Ptr:
		buf.WriteString("*")
		writeTypeName(buf, t.Elem())
	default:
		buf.WriteString(t.String())
	}
}

func writeGoString(buf *bytes.Buffer, s string) {
	if !strings.ContainsAny(s, "\n\r\t\\\"") {
		buf.WriteString(`"`)
		buf.WriteString(s)
		buf.WriteString(`"`)
		return
	}
	fmt.Fprintf(buf, "%q", s)
}

func isZeroValue(v reflect.Value) bool {
	switch v.Kind() {
	case reflect.Bool:
		return !v.Bool()
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return v.Int() == 0
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return v.Uint() == 0
	case reflect.Float32, reflect.Float64:
		return v.Float() == 0
	case reflect.String:
		return v.String() == ""
	case reflect.Map, reflect.Slice:
		return v.IsNil() || v.Len() == 0
	case reflect.Ptr, reflect.Interface:
		return v.IsNil()
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			if v.Type().Field(i).IsExported() && !isZeroValue(v.Field(i)) {
				return false
			}
		}
		return true
	default:
		return false
	}
}
