import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'doc',
        id: 'intro',
      },
      items: [
        'getting-started/installation',
        'getting-started/configuration',
        'getting-started/quick-start',
      ],
    },
    {
      type: 'category',
      label: 'User Guide',
      items: [
        'user-guide/concepts',
        'user-guide/common-differences',
        'user-guide/command-model',
        'user-guide/discovery',
        'user-guide/resource-operations',
        'user-guide/output',
        {
          type: 'category',
          label: 'Resource-specific Optimizations',
          link: {
            type: 'doc',
            id: 'user-guide/resource-optimizations/index',
          },
          items: [
            'user-guide/resource-optimizations/ecs',
            'user-guide/resource-optimizations/ack',
            'user-guide/resource-optimizations/vpc',
            'user-guide/resource-optimizations/lingjun',
          ],
        },
        'user-guide/openapi-call',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'category',
          label: 'Products',
          items: [{type: 'autogenerated', dirName: 'reference/resources'}],
        },
        'reference/resource-coverage',
        'reference/commands',
        'reference/errors',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        'contributing/resource-specs',
      ],
    },
  ],
};

export default sidebars;
